### ISSUE TITLE
 [[object HTMLFormElement]] issue

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/stacksavings-editor#2]
Karanpreet's Issue
[[object HTMLFormElement]] appears against the editable tags in test URL

https://karanpreet-stacksavingsdev.c9users.io/templates/servicejoin/index.html?page=servicejoin_karanpreet&auth_token=servicejoinauth

screenshot: http://prntscr.com/bvt774

**Comment by stacksavings** [comment]
I think this may be due to missing Jquery but not sure.

**Comment by stacksavings** [comment]
Please refer to this: https://youtu.be/UFsUDSREqjo
